### ISSUE TITLE
Insertion and deletion in an array

### ISSUE THREAD

**Issue by panka17** [king04aman/hacktoberfest2022#17]
I want to add insertion and deletion in an array code in C++. 
Please assign it to me @king04aman

**Comment by lotfijb** [comment]
I want to add insertion and deletion in an array in Python
Assign it to me please @king04aman

**Comment by anuragwadhwa22** [comment]
I want to add insertion and deletion in an array in java
Please assign it to me @king04aman

**Comment by devUT27** [comment]
I want to add insertion and deletion in an array in C
Please assign it to me @king04aman

**Comment by anuragwadhwa22** [comment]
PR for insertion and deletion in an array in java: https://github.com/king04aman/hacktoberfest2022/pull/46
@king04aman you can have a look

**Comment by Kraken-ops** [comment]
I want to contribute to this issue, please assign me.
