### ISSUE TITLE
Write a program to check a given number is armstrong or not.

### ISSUE THREAD

**Issue by kart027** [king04aman/hacktoberfest2022#48]
I would like to write code for Write a program to check a given number is armstrong or not in cpp

**Comment by kart027** [comment]
if possible please assign it to me under label hacktoberfest

**Comment by roushan-rks** [comment]
@king04aman assign me ...

**Comment by Kraken-ops** [comment]
I want to contribute to this issue. Please assign me.

**Comment by Murtaza-Farooqui** [comment]
I want to contribute to this issue. Please assign me.

**Comment by SanjoySaha24** [comment]
I want to contribute to this issue. Please assign me @king04aman .

**Comment by Aman-Sekhon** [comment]
Hello @king04aman,
I have done 200+ DSA based question so far. I would like to attempt this issue. Assign me this issue.
Thanks

**Comment by 1Alisha** [comment]
I want to contribute to this issue. Please assign me @king04aman .

**Comment by Vivek-raj-64** [comment]
Please assign it to me @king04aman under hacktoberfest label.

**Comment by ChakitBhandari** [comment]
Hello @king04aman,
I would like to contribute my code in C++ for this issue under Hacktoberfest2022.
Could you please assign me with this issue?
Thank you!!

**Comment by vaibhav23agrawal** [comment]
Sir if possible please assign it to me under label hacktoberfest

**Comment by jaywyawhare** [comment]
Submitted in RP #241

**Comment by Man07har** [comment]
Hey would like to contribute in this would you please assign it to me

**Comment by nityabarwi** [comment]
Hello
I want to contribute in this project in Python.
Can you please assign me the issue ?

**Comment by Monisha0707** [comment]
Hello @king04aman !
I want to add efficient solution to this problem under Hacktoberfest 2022. Please assign this to me.

**Comment by Abhinav092003** [comment]
can u please assign to me i wont be disappoint you..plzz assign to me🙏

**Comment by lohani25** [comment]
please assign me this task

**Comment by palprashant2002** [comment]
Please assign this issue to me...

**Comment by imNilabja** [comment]
I would like to do this task ,can you assign me.

**Comment by sabhisharma-ise** [comment]
Can you assign me this issue?
