### ISSUE TITLE
check if array is sorted and rotated

### ISSUE THREAD

**Issue by coder-mohan** [king04aman/hacktoberfest2022#49]
hey @king04aman  I want to add code in c++ for the problem "check if array is sorted and rotated"

**Comment by coder-mohan** [comment]
hey @king04aman  i have added the solution of the problem you can check and merge with hacktoberfest label

**Comment by roushan-rks** [comment]
@king04aman assign me ....

**Comment by Kraken-ops** [comment]
I want to contribute to this issue. Please assign me.

**Comment by 18Ayushi** [comment]
@king04aman i want to work on this issue, please assign me.

**Comment by SanjoySaha24** [comment]
I want to contribute to this issue. Please assign me @king04aman

**Comment by 1Alisha** [comment]
I want to contribute to this issue. Please assign me.

**Comment by soham2312** [comment]
I want to contribute to this issue. Please assign me.

**Comment by Sampurankishoresrivastava** [comment]
I want to contribute to this issue in c. Please assign me.

**Comment by ChakitBhandari** [comment]
Hello @king04aman,
I would like to contribute my code in C++ for this issue under Hacktoberfest2022.
Could you please assign me with this issue?
Thank you!!

**Comment by ritushreedas2002** [comment]
hello @king04aman 
I want to add code in c++ for the problem "check if array is sorted and rotated"...
thank u

**Comment by ritushreedas2002** [comment]
do assign me under the label hacktoberfest

**Comment by Vivek-raj-64** [comment]
Hey @king04aman ,
I want to contribute in this project. Please assign it to me under hacktoberfest-accepted label.

**Comment by palprashant2002** [comment]
Please assign this issue to me...

**Comment by sabhisharma-ise** [comment]
Can you assign me this issue?

**Comment by shubh1007** [comment]
please assign me
