### ISSUE TITLE
I want to add BMI Calculator Program in Java

### ISSUE THREAD

**Issue by minhaj-313** [king04aman/hacktoberfest2022#58]
BMI Calculator program is used to find body mass index

**Comment by minhaj-313** [comment]
Please aasign it to me under Hacktoberfest

**Comment by minhaj-313** [comment]
Thank You

**Comment by minhaj-313** [comment]
Thank You

**Comment by Sandyy07** [comment]
Kindly Please assign me this issue.

**Comment by executionBeast** [comment]
@king04aman Please assign me this issue. I can do it.
