### ISSUE TITLE
Cypher algorithm program

### ISSUE THREAD

**Issue by narwar-veer** [king04aman/hacktoberfest2022#91]
I want to add cypher algorithm program which is used to encrypt and decrypt the messages, pls assign me the same.

**Comment by narwar-veer** [comment]
I have done my work , pls accept my pull request!!

**Comment by ChakitBhandari** [comment]
Hello @king04aman,
I would like to contribute my code in C++ for this issue under Hacktoberfest2022.
Could you please assign me with this issue?
Thank you!!

**Comment by Arika008** [comment]
Please check my PR #285
